// Bilingual menu data for Taqueria El Costeño
// Each item: { name, es, en, price }
const MENU_DATA = [
  {
    id: "breakfast",
    es: "Desayunos",
    en: "Breakfast",
    note: "Served with refried beans, rice & tortillas",
    items: [
      { name: "Huevos a la Mexicana", en: "Scrambled Eggs mixed with jalapeno, tomato & onion.", es: "Dos huevos estrellados sobre tortilla, bañados en salsa ranchera de tomate y chile.", price: "12.50" },
      { name: "Huevos con Jamon", en: "Scrambled Eggs and Ham", es: "Totopos crujientes guisados en salsa verde o roja, crema, queso fresco y cebolla.", price: "13.00" },
      { name: "Huevos con Tocino", en: "Scrambled Eggs and Bacon.", es: "Huevos revueltos con jitomate, cebolla y chile serrano.", price: "11.75" },
      { name: "Huevos con Chorizo", en: "Scrambled eggs with Mexican chorizo.", es: "Huevos revueltos con chorizo casero estilo mexicano.", price: "12.25" },
      { name: "Huevos Rancheros", en: "Sunny side up eggs, topped with salsa ranchera.", es: "Carne deshebrada y seca, salteada con huevo, jitomate y cebolla.", price: "13.50" },
      { name: "Chilaquiles Verdes o Rojos", en: "Fried tortilla chips, choice of green and red salsa. Topped with queso, sour cream, & onion.", es: "Bolillo abierto con frijoles refritos, queso derretido y pico de gallo.", price: "10.50" },
    ],
  },
  {
    id: "tacos",
    es: "Tacos",
    en: "Tacos",
    note: "Topped with fresh diced onions & cilantro or lettuce & tomato",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "3.50" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "3.50" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "3.50" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "3.50" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "3.50" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "3.50" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Corte de res cocinado a fuego lento en su jugo, suave y sabroso.", price: "3.50" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Chorizo mexicano casero, sazonado con chiles y especias.", price: "3.50" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "4.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "4.00" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "4.50" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "4.50" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "4.50" },
    ],
  },
  {
    id: "sopes",
    es: "Sopes",
    en: "Sopes",
    note: "Thick handmade masa topped with beans, lettuce, tomatoes, onions, cilantro, cheese, sour cream, & avocado",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "6.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "6.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "6.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "6.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "6.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "6.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Corte de res cocinado a fuego lento en su jugo, suave y sabroso.", price: "6.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Chorizo mexicano casero, sazonado con chiles y especias.", price: "6.00" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.50" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "6.50" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },
    ],
  },
  {
    id: "tortas",
    es: "Tortas",
    en: "Tortas",
    note: "Mexican sandwich with beans, lettuce, tomatoes, onion, cilantro, sour cream & avocado",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "9.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "9.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "9.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "9.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "9.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "9.00" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "10.0" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "10.00" },
      { name: "Milanesa de Res", en: "Breaded Beef", es: "Pollo a la parrilla marinado con ajo y limón.", price: "10.00" },
      { name: "Milanesa de Pollo", en: "Breaded Chicken", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "10.00" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },    
    ],
  },
  {
    id: "burritos",
    es: "Burritos",
    en: "Burritos",
    note: "Filled with beans, lettuce, tomato, onion, cilantro, cream and cheese",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "11.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "11.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "11.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "11.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "11.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "11.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Corte de res cocinado a fuego lento en su jugo, suave y sabroso.", price: "11.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Chorizo mexicano casero, sazonado con chiles y especias.", price: "11.00" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "12.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "12.00" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "14.00" },
    ],
  },
  {
    id: "tostadas",
    es: "Tostadas",
    en: "Tostadas",
    note: "Crispy fried tortilla · Tortilla frita crujiente",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "5.50" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "5.50" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "5.50" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "5.50" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "5.50" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "5.50" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Corte de res cocinado a fuego lento en su jugo, suave y sabroso.", price: "5.50" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Chorizo mexicano casero, sazonado con chiles y especias.", price: "5.50" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "6.00" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.50" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.50" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.50" },
    ],
  },
  {
    id: "gorditas",
    es: "Gorditas",
    en: "Gorditas",
    note: "Thick masa pockets griddled to order · Masa gruesa rellena, hecha en comal",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado en achiote y especias, cocinado al trompo, con piña.", price: "6.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec de res a la parrilla, sazonado con sal de mar y limón.", price: "6.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Cerdo confitado lentamente hasta quedar jugoso por dentro y dorado por fuera.", price: "6.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Lengua de res cocida hasta quedar tierna, picada finamente.", price: "6.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Tripa de res frita en su grasa hasta quedar crujiente.", price: "6.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Estómago de cerdo cocinado lentamente, con un sabor profundo y rico.", price: "6.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Corte de res cocinado a fuego lento en su jugo, suave y sabroso.", price: "6.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Chorizo mexicano casero, sazonado con chiles y especias.", price: "6.00" },
      { name: "Tripa", en: "Beef tripe", es: "Pollo a la parrilla marinado con ajo y limón.", price: "6.50" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de cabeza de res al vapor, increíblemente tierna.", price: "6.50" },
      { name: "Lengua", en: "Beef tongue", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },
      { name: "Camarones", en: "Shrimp", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },   
      { name: "Pescado", en: "Fish", es: "Pollo a la parrilla marinado con ajo y limón.", price: "7.50" },
    ],
  },
  {
    id: "soups",
    es: "Caldos",
    en: "Soups",
    note: "",
    items: [
      { name: "Caldo de Res", en: "Beef Soup", es: "Caldo de maíz con cerdo, chile guajillo, lechuga, rábano y orégano.", price: "16.00" },
      { name: "Caldo de Pollo", en: "Chicken Soup", es: "Caldo tradicional de panza de res con maíz pozolero (fines de semana).", price: "15.00" },
      { name: "Caldo de Pescado", en: "Fish Soup", es: "Caldo de res con verduras de la huerta y arroz.", price: "17.00" },
      { name: "Caldo de Camarones", en: "Shrimp Soup", es: "Caldo de pollo con arroz, aguacate y limón.", price: "17.00" },
      
    ],
  },
  {
    id: "platillos",
    es: "Platillos",
    en: "Platillos",
    note: "Served with rice, beans, salad and tortillas.",
    items: [
      { name: "Carne Asada", en: "Grilled skirt skate with grilled onion, jalapeno, and nopales", es: "Pollo bañado en mole poblano de la casa con ajonjolí.", price: "22.00" },
      { name: "Carne Tampiquena", en: "Grilled skirt skate with one cheese enchilada.", es: "Chiles poblanos rellenos de queso, capeados, en salsa de jitomate.", price: "22.00" },
      { name: "Mar y Tierra", en: "Three chicken enchiladas in green salsa, crema and cheese.", es: "Tres enchiladas de pollo en salsa verde, crema y queso.", price: "25.00" },
      { name: "Costillas de Res", en: "Grilled beef ribs.", es: "Tres enchiladas de pollo bañadas en mole.", price: "23.00" },
      { name: "Bistec a la Mexicana", en: "Steak sauted with onion, tomato, and jalapeno.", es: "Bistec empanizado y frito con ensalada y limón.", price: "21.00" },
      { name: "Bistec Suizo", en: "Grilled steak with bacon, green, red perppers, and cheese.", es: "", price: "23.00"},
      { name: "Fajita de Res", en: "Grilled steak cooked with bell peppers, onions, and tomatos.", es: "", price: "22.00"},
      { name: "Fajitas de Pollo", en: "Grilled chicken cooked with bell peppers, onions, and tomatoes.", es: "", price: "20.00"},
      { name: "Fajitas de Camaron", en: "Grilled shrimp, cooked with bell peppers, onions, and tomatoes", es: "", price: "25.00"},
      { name: "Guisado de puerco en salsa verde", en: "Pork stew with green salsa.", es: "", price: "14.00"},
      { name: "Guisado de luenga", en: "Beef tongue in green salsa", es: "", price: "25.00"},
      { name: "Enchiladas Verdes", en: "Your choice of Chiockenm, Steak or Ground Beef filled corn tortillas", es: "", price: "17.00"},      
      { name: "Flautas de Pollo", en: "3 filed corn tortilla rolled and deep fried, filled with chicken. Topped with sour cream, lettuce, tomato, onion, avocado and cheese", es: "", price: "17.00"},
      { name: "Pechuga a la plancha", en: "Grilled chicken breast", es: "", price: "18.00"}
    ],
  },
  {
    id: "dinners",
    es: "Cenas",
    en: "Dinners",
    note: "",
    items: [
      { name: "Taco Dinner", en: "3 tacos, carne asada, al pastor, tripa or cabeza", es: "", price: "14.00"} 
    ],
  },
  {
    id: "quesadillas",
    es: "Quesadillas",
    en: "Quesadillas",
    note: "Flour tortilla with melted Oaxaca cheese · Tortilla de harina con queso Oaxaca derretido",
    items: [
      { name: "Quesadilla de Asada", en: "With grilled steak.", es: "Con bistec a la parrilla.", price: "10.95" },
      { name: "Quesadilla de Pastor", en: "With al pastor pork and pineapple.", es: "Con cerdo al pastor y piña.", price: "10.50" },
      { name: "Quesadilla de Champiñones", en: "With mushrooms sautéed with garlic and epazote.", es: "Con hongos salteados al ajo y epazote.", price: "9.50" },
      { name: "Quesadilla de Flor de Calabaza", en: "With squash blossoms and Oaxaca cheese.", es: "Con flor de calabaza y queso Oaxaca.", price: "10.25" },
      { name: "Quesadilla de Huitlacoche", en: "With corn truffle (huitlacoche) and epazote.", es: "Con huitlacoche y epazote.", price: "10.95" },
    ],
  },
  {
    id: "drinks",
    es: "Bebidas",
    en: "Drinks",
    note: "Aguas frescas made fresh daily · Aguas frescas hechas a diario",
    items: [
      { name: "Horchata", en: "Rice water with cinnamon and vanilla.", es: "Agua de arroz con canela y vainilla.", price: "4.50" },
      { name: "Jamaica", en: "Chilled hibiscus flower water.", es: "Agua de flor de jamaica fría.", price: "4.50" },
      { name: "Tamarindo", en: "Sweet-tart tamarind water.", es: "Agua de tamarindo agridulce.", price: "4.50" },
      { name: "Michelada Costeña", en: "Beer with lime, chamoy, hot sauces, Tajín-rimmed.", es: "Cerveza con limón, chamoy, salsas y escarchado de Tajín.", price: "9.50" },
      { name: "Jarritos", en: "Mexican soda — assorted flavors.", es: "Refresco mexicano (varios sabores).", price: "3.50" },
      { name: "Mexican Coca-Cola", en: "Coca-Cola made with cane sugar.", es: "Coca-Cola hecha con azúcar de caña.", price: "3.95" },
      { name: "Café de Olla", en: "Coffee with cinnamon and piloncillo, brewed in clay.", es: "Café con canela y piloncillo, en olla de barro.", price: "3.75" },
    ],
  },
  {
    id: "sides",
    es: "Acompañamientos",
    en: "Sides",
    items: [
      { name: "Arroz Mexicano", en: "Red rice with vegetables.", es: "Arroz rojo con verduras.", price: "3.50" },
      { name: "Frijoles Charros", en: "Beans with bacon, chorizo and chile.", es: "Frijoles con tocino, chorizo y chile.", price: "4.50" },
      { name: "Frijoles Refritos", en: "Refried beans with queso fresco.", es: "Frijoles refritos con queso fresco.", price: "3.50" },
      { name: "Guacamole", en: "Mashed avocado with lime, onion and cilantro.", es: "Aguacate machacado con limón, cebolla y cilantro.", price: "5.95" },
      { name: "Chips & Salsa", en: "House-fried tortilla chips with house salsa.", es: "Totopos recién hechos con salsa de la casa.", price: "4.50" },
      { name: "Cebollitas Asadas", en: "Grilled spring onions with lime.", es: "Cebollas cambray a la parrilla con limón.", price: "4.95" },
    ],
  },
  {
    id: "weekend",
    es: "Especiales del Fin de Semana",
    en: "Weekend Specials",
    note: "Saturday & Sunday only · Sábado y domingo solamente",
    items: [
      { name: "Barbacoa de Res", en: "Beef steamed overnight in maguey leaves.", es: "Res cocida al vapor toda la noche en hojas de maguey.", price: "17.95" },
      { name: "Birria Estilo Jalisco", en: "Goat or beef stew in guajillo chiles, with consommé.", es: "Guiso de chivo o res en chiles guajillos, con consomé.", price: "17.50" },
      { name: "Menudo Rojo", en: "Beef tripe and hominy soup with red chile.", es: "Caldo de panza de res con maíz pozolero y chile rojo.", price: "13.95" },
      { name: "Pozole Blanco", en: "Traditional white pozole, served with all the fixings.", es: "Pozole tradicional sin chile rojo, con todos los acompañamientos.", price: "13.50" },
      { name: "Tamales", en: "Homemade tamales: red, green, mole or rajas with cheese.", es: "Tamales caseros: rojo, verde, mole o rajas con queso.", price: "4.50" },
    ],
  },
];

export default MENU_DATA;
