// Bilingual menu data for Taqueria El Costeño
// Each item: { name, es, en, price }
const MENU_DATA = [
  {
    id: "breakfast",
    es: "Desayunos",
    en: "Breakfast",
    note: "Served with refried beans, rice & tortillas",
    items: [
      { name: "Huevos a la Mexicana", en: "Scrambled Eggs mixed with jalapeno, tomato & onion.", es: "Huevos revueltos con jalapeño, jitomate y cebolla.", price: "12.50" },
      { name: "Huevos con Jamon", en: "Scrambled Eggs and Ham", es: "Huevos revueltos con jamón.", price: "13.00" },
      { name: "Huevos con Tocino", en: "Scrambled Eggs and Bacon.", es: "Huevos revueltos con tocino.", price: "11.75" },
      { name: "Huevos con Chorizo", en: "Scrambled eggs with Mexican chorizo.", es: "Huevos revueltos con chorizo mexicano.", price: "12.25" },
      { name: "Huevos Rancheros", en: "Sunny side up eggs, topped with salsa ranchera.", es: "Huevos estrellados con salsa ranchera.", price: "13.50" },
      { name: "Chilaquiles Verdes o Rojos", en: "Fried tortilla chips, choice of green and red salsa. Topped with queso, sour cream, & onion.", es: "Totopos fritos en salsa verde o roja, con queso, crema y cebolla.", price: "10.50" },
    ],
  },
  {
    id: "tacos",
    es: "Tacos",
    en: "Tacos",
    note: "Topped with fresh diced onions & cilantro or lettuce & tomato",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "3.50" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "3.50" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "3.50" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "3.50" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "3.50" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "3.50" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Chicharrón en salsa verde.", price: "3.50" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Rajas de chile poblano o nopales.", price: "3.50" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "4.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "4.00" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "4.50" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "4.50" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "4.50" },
    ],
  },
  {
    id: "sopes",
    es: "Sopes",
    en: "Sopes",
    note: "Thick handmade masa topped with beans, lettuce, tomatoes, onions, cilantro, cheese, sour cream, & avocado",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "6.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "6.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "6.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "6.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "6.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "6.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Chicharrón en salsa verde.", price: "6.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Rajas de chile poblano o nopales.", price: "6.00" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "6.50" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "6.50" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "7.50" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "7.50" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "7.50" },
    ],
  },
  {
    id: "tortas",
    es: "Tortas",
    en: "Tortas",
    note: "Mexican sandwich with beans, lettuce, tomatoes, onion, cilantro, sour cream & avocado",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "9.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "9.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "9.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "9.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "9.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "9.00" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "10.0" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "10.00" },
      { name: "Milanesa de Res", en: "Breaded Beef", es: "Bistec empanizado.", price: "10.00" },
      { name: "Milanesa de Pollo", en: "Breaded Chicken", es: "Pollo empanizado.", price: "10.00" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "14.00" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "14.00" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "14.00" },
    ],
  },
  {
    id: "burritos",
    es: "Burritos",
    en: "Burritos",
    note: "Filled with beans, lettuce, tomato, onion, cilantro, cream and cheese",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "11.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "11.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "11.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "11.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "11.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "11.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Chicharrón en salsa verde.", price: "11.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Rajas de chile poblano o nopales.", price: "11.00" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "12.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "12.00" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "14.00" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "14.00" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "14.00" },
    ],
  },
  {
    id: "tostadas",
    es: "Tostadas",
    en: "Tostadas",
    note: "Crispy fried tortilla · Tortilla frita crujiente",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "5.50" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "5.50" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "5.50" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "5.50" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "5.50" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "5.50" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Chicharrón en salsa verde.", price: "5.50" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Rajas de chile poblano o nopales.", price: "5.50" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "6.00" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "6.00" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "6.50" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "6.50" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "6.50" },
    ],
  },
  {
    id: "gorditas",
    es: "Gorditas",
    en: "Gorditas",
    note: "Thick masa pockets griddled to order · Masa gruesa rellena, hecha en comal",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "6.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "6.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "6.00" },
      { name: "Cabeza", en: "Mexican beef head.", es: "Cabeza de res.", price: "6.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "6.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "6.00" },
      { name: "Chicharron", en: "Fried pork skin in green salsa", es: "Chicharrón en salsa verde.", price: "6.00" },
      { name: "Rajas/Nopales", en: "Roasted poblano peppers or traditional prickly pear cactus.", es: "Rajas de chile poblano o nopales.", price: "6.00" },
      { name: "Tripa", en: "Beef tripe", es: "Tripa de res.", price: "6.50" },
      { name: "Cecina", en: "Salted and air-cured beef", es: "Carne de res salada y curada al aire.", price: "6.50" },
      { name: "Lengua", en: "Beef tongue", es: "Lengua de res.", price: "7.50" },
      { name: "Camarones", en: "Shrimp", es: "Camarones.", price: "7.50" },
      { name: "Pescado", en: "Fish", es: "Pescado.", price: "7.50" },
    ],
  },
  {
    id: "soups",
    es: "Caldos",
    en: "Soups",
    note: "",
    items: [
      { name: "Caldo de Res", en: "Beef Soup", es: "Caldo de res.", price: "16.00" },
      { name: "Caldo de Pollo", en: "Chicken Soup", es: "Caldo de pollo.", price: "15.00" },
      { name: "Caldo de Pescado", en: "Fish Soup", es: "Caldo de pescado.", price: "17.00" },
      { name: "Caldo de Camarones", en: "Shrimp Soup", es: "Caldo de camarones.", price: "17.00" },

    ],
  },
  {
    id: "platillos",
    es: "Platillos",
    en: "Platillos",
    note: "Served with rice, beans, salad and tortillas.",
    items: [
      { name: "Carne Asada", en: "Grilled skirt skate with grilled onion, jalapeno, and nopales", es: "Arrachera a la parrilla con cebollita, jalapeño y nopales.", price: "22.00" },
      { name: "Carne Tampiquena", en: "Grilled skirt skate with one cheese enchilada.", es: "Arrachera a la parrilla con una enchilada de queso.", price: "22.00" },
      { name: "Mar y Tierra", en: "Three chicken enchiladas in green salsa, crema and cheese.", es: "Tres enchiladas de pollo en salsa verde, crema y queso.", price: "25.00" },
      { name: "Costillas de Res", en: "Grilled beef ribs.", es: "Costillas de res a la parrilla.", price: "23.00" },
      { name: "Bistec a la Mexicana", en: "Steak sauted with onion, tomato, and jalapeno.", es: "Bistec salteado con cebolla, jitomate y jalapeño.", price: "21.00" },
      { name: "Bistec Suizo", en: "Grilled steak with bacon, green, red perppers, and cheese.", es: "Bistec a la parrilla con tocino, pimientos y queso.", price: "23.00"},
      { name: "Fajita de Res", en: "Grilled steak cooked with bell peppers, onions, and tomatos.", es: "Fajitas de res a la parrilla con pimientos, cebolla y jitomate.", price: "22.00"},
      { name: "Fajitas de Pollo", en: "Grilled chicken cooked with bell peppers, onions, and tomatoes.", es: "Fajitas de pollo a la parrilla con pimientos, cebolla y jitomate.", price: "20.00"},
      { name: "Fajitas de Camaron", en: "Grilled shrimp, cooked with bell peppers, onions, and tomatoes", es: "Camarones a la parrilla con pimientos, cebolla y jitomate.", price: "25.00"},
      { name: "Guisado de puerco en salsa verde", en: "Pork stew with green salsa.", es: "Guisado de cerdo en salsa verde.", price: "14.00"},
      { name: "Guisado de luenga", en: "Beef tongue in green salsa", es: "Lengua de res en salsa verde.", price: "25.00"},
      { name: "Enchiladas Verdes", en: "Your choice of Chiockenm, Steak or Ground Beef filled corn tortillas", es: "Enchiladas de pollo, bistec o picadillo a tu elección.", price: "17.00"},
      { name: "Flautas de Pollo", en: "3 filed corn tortilla rolled and deep fried, filled with chicken. Topped with sour cream, lettuce, tomato, onion, avocado and cheese", es: "3 flautas de maíz rellenas de pollo, fritas. Con crema, lechuga, jitomate, cebolla, aguacate y queso.", price: "17.00"},
      { name: "Pechuga a la plancha", en: "Grilled chicken breast", es: "Pechuga de pollo a la plancha.", price: "18.00"}
    ],
  },
  {
    id: "dinners",
    es: "Cenas",
    en: "Dinners",
    note: "",
    items: [
      { name: "Taco Dinner", en: "3 Tacos. Carne Asada, Al Pastor, Tripa or Cabeza", es: "3 Tacos. Carne Asada, Al Pastor, Tripa o Cabeza.", price: "14.00"},
      { name: "Sope Dinner", en: "2 Sopes. Carne Asada, Al Pastor, Picadillo or Pollo", es: "2 Sopes. Carne Asada, Al Pastor, Picadillo o Pollo.", price: "15.00"},
      { name: "Gordita Dinner", en: "2 Gorditas. Carne Asada, Al Pastor, Tripa or Cabeza", es: "2 Gorditas. Carne Asada, Al Pastor, Tripa o Cabeza.", price: "15.00"},
      { name: "Burrito Dinner", en: "Carne Asada, Al Pastor, Picadillo or Pollo", es: "Carne Asada, Al Pastor, Picadillo o Pollo.", price: "13.50"},
      { name: "Torta Dinner", en: "Carne Asada. Al Pastor, Picadillo, Pollo or Milanesa (+$1.00)", es: "Carne Asada, Al Pastor, Picadillo, Pollo o Milanesa (+$1.00).", price: "12.00"}
    ],
  },
  {
    id: "quesadillas",
    es: "Quesadillas",
    en: "Quesadillas",
    note: "3 Quesadillas with flour, rice, beans and green salad",
    items: [
      { name: "Al Pastor", en: "Marinated Pork", es: "Cerdo marinado.", price: "16.00" },
      { name: "Carne Asada", en: "Grilled Steak", es: "Bistec a la parrilla.", price: "16.00" },
      { name: "Pollo", en: "Grtilled Chicken.", es: "Pollo a la parrilla.", price: "16.00" },
      { name: "Picadillo", en: "Ground beef.", es: "Carne molida.", price: "16.00" },
      { name: "Chorizo", en: "Mexican sausage", es: "Chorizo mexicano.", price: "16.00" },
      { name: "Cheese Only", en: "Cheese Only", es: "Solo queso.", price: "12.00" }
    ],
  },
  {
    id: "drinks",
    es: "Bebidas",
    en: "Drinks",
    note: "Aguas frescas made fresh daily · Aguas frescas hechas a diario",
    items: [
      { name: "Coffee or Tea", en: "Coffee or Tea", es: "Café o Té", price: "3.00" },
      { name: "Mexican Soda", en: "Jarritos, Sidral Mundet, Topo Chico", es: "Jarritos, Sidral Mundet, Topo Chico", price: "3.50" },
      { name: "Mexican Coke", en: "Coca-Cola made with real cane sugar", es: "Coca-cola de botella", price: "4.00" },
      { name: "Canned Soda", en: "Coca-cola. Sprite, Pepsi. Squirt, Crush, Seven-up", es: "Coca-cola. Sprite, Pepsi. Squirt, Crush, Seven-up", price: "1.75" },
      { name: "Aguas Frescas", en: "Horchata or Jamaica", es: "Horchata o Jamaica", price: "4.00/6.00" }
    ],
  },
  {
    id: "sides",
    es: "Acompañamientos",
    en: "Sides",
    items: [
      { name: "Arroz", en: "Rice", es: "Arroz", price: "4.00" },
      { name: "Frijoles", en: "Beans", es: "Frijoles", price: "4.00" },
      { name: "Chiles toreados", en: "Grilled jalapenos", es: "Chiles toreados", price: "2.00" },
      { name: "Guacamole", en: "", es: "", price: "MP" },
      { name: "Chips & Salsa", en: "House-fried tortilla chips with house salsa.", es: "Totopos recién hechos con salsa.", price: "5.00" },
      { name: "French Fries", en: "French Fries", es: "Papas fritas", price: "4.00" },
      { name: "Cebollitas", en: "Grilled onions", es: "Cebollitas asadas", price: "4.00" }
    ],
  },
];

export default MENU_DATA;
